### ISSUE TITLE
Where to find the annotation

### ISSUE THREAD

**Issue by shelkmike** [lurebgi/chicken-T2T#1]
This is not actually an issue related to the code, but I think it's a good place for this question. Where can I find the annotation of this T2T assembly?

**Comment by lurebgi** [comment]
You can download the latest genome and annotation versions using this [link](https://www.dropbox.com/scl/fo/plq2tm2w9lzlk0ua1rzph/h?dl=0&rlkey=l6z3rgmjs7ec9azun8nundnzl)

**Comment by shelkmike** [comment]
Thank you.
