### ISSUE TITLE
issue to produce the first version of primary contigs

### ISSUE THREAD

**Issue by shengs-UCAS** [lurebgi/chicken-T2T#3]
thanks for your work.

but I encountered problems while producing the first version of the genome.
how  did you aligned hifi_pri against ont_pri and replaced the homologous sequences in ont_pri with hifi_pri sequences; when a hifi_pri contig spans the ends of two ont_pri contigs, and manually joined the ont_pri contigs
any code or software is appreciated.

**Comment by lurebgi** [comment]
Hi, we used nucmer to align the sequences. A few scripts are available here https://github.com/comery/Trio_chicken that we used to replace the contigs.

**Comment by shengs-UCAS** [comment]
thanks a lot!
